---
apiVersion: v1
kind: Namespace
metadata:
  name: k8sproxy
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8sproxy
  namespace: k8sproxy
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/mmd1999/k8sproxy/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8sproxy
  namespace: k8sproxy
spec:
  interval: 30m
  chart:
    spec:
      chart: k8sproxy
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: k8sproxy
        namespace: k8sproxy
      interval: 12h
  values:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      hosts:
      - host: localhost
        paths:
          - path: /k8sproxy(/|$)(.*)
            pathType: ImplementationSpecific