---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 30m
  chart:
    spec:
      chart: metrcis-server
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: metrics-server
      interval: 12h
  values:
    fullnameOverride: metrics-server

    apiService:
      insecureSkipTLSVerify: true

    defaultArgs:
      - --cert-dir=/tmp
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
      - --kubelet-insecure-tls